### ISSUE TITLE
Suggestion - instead of strong, use span

### ISSUE THREAD

**Issue by jzhu01** [nkattis/prj-rev-bwfs-dasmoto#3]
Seen here: https://github.com/nkattis/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsandCrafts/index.html#L14

Since the strong tag is actually styling the content inside of it, I would recommend using span instead. Our goal as developers is to keep all the styling in the CSS, and leave the structuring of content in the HTML. ^_^

**Comment by nkattis** [comment]
Brilliant, hadn't event thought of that (I'd interpreted span as merely structural) but will definitely go this route in the future.
